"""Aggiunto codice_fiscale

Revision ID: 1c8fa103024d
Revises: 
Create Date: 2025-03-10 10:39:56.368046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8fa103024d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attestato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_discente', sa.String(length=100), nullable=False),
    sa.Column('corso', sa.String(length=100), nullable=False),
    sa.Column('data_attestato', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progetto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('ente', sa.String(length=100), nullable=True),
    sa.Column('inizio_progetto', sa.Date(), nullable=True),
    sa.Column('fine_progetto', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('test_preliminare', sa.String(length=255), nullable=True),
    sa.Column('test_postcorso', sa.String(length=255), nullable=True),
    sa.Column('docente', sa.String(length=100), nullable=False),
    sa.Column('ore_totali', sa.Integer(), nullable=False),
    sa.Column('progetto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['progetto_id'], ['progetto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=False),
    sa.Column('genere', sa.String(length=10), nullable=True),
    sa.Column('fascia_eta', sa.String(length=50), nullable=True),
    sa.Column('ruolo', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('cellulare', sa.String(length=20), nullable=True),
    sa.Column('progetto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['progetto_id'], ['progetto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_fiscale'),
    sa.UniqueConstraint('email')
    )
    op.create_table('iscrizione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discente_id', sa.Integer(), nullable=False),
    sa.Column('corso_id', sa.Integer(), nullable=False),
    sa.Column('ore_frequentate', sa.Integer(), nullable=True),
    sa.Column('test_superato', sa.Boolean(), nullable=True),
    sa.Column('punteggio_test', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corso_id'], ['corso.id'], ),
    sa.ForeignKeyConstraint(['discente_id'], ['discente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lezione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corso_id', sa.Integer(), nullable=False),
    sa.Column('data_lezione', sa.Date(), nullable=False),
    sa.Column('orario', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['corso_id'], ['corso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_risultati_postcorso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discente_id', sa.Integer(), nullable=False),
    sa.Column('corso_id', sa.Integer(), nullable=False),
    sa.Column('risposte', sa.JSON(), nullable=False),
    sa.Column('data_compilazione', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corso_id'], ['corso.id'], ),
    sa.ForeignKeyConstraint(['discente_id'], ['discente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_risultato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discente_id', sa.Integer(), nullable=False),
    sa.Column('corso_id', sa.Integer(), nullable=False),
    sa.Column('punteggio_ottenuto', sa.Integer(), nullable=False),
    sa.Column('superato', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['corso_id'], ['corso.id'], ),
    sa.ForeignKeyConstraint(['discente_id'], ['discente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presenza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lezione_id', sa.Integer(), nullable=False),
    sa.Column('discente_id', sa.Integer(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['discente_id'], ['discente.id'], ),
    sa.ForeignKeyConstraint(['lezione_id'], ['lezione.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presenza')
    op.drop_table('test_risultato')
    op.drop_table('test_risultati_postcorso')
    op.drop_table('lezione')
    op.drop_table('iscrizione')
    op.drop_table('discente')
    op.drop_table('corso')
    op.drop_table('progetto')
    op.drop_table('attestato')
    # ### end Alembic commands ###
