"""Aggiunta email e telefono al modello Discente

Revision ID: 40947dc72616
Revises: 1c8fa103024d
Create Date: 2025-03-15 13:32:36.112738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40947dc72616'
down_revision = '1c8fa103024d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discente', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
