"""Correzione relazioni in models.py

Revision ID: 8a8d6433ff57
Revises: c259fa95b84f
Create Date: 2025-03-06 11:08:26.001740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8d6433ff57'
down_revision = 'c259fa95b84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corso', schema=None) as batch_op:
        batch_op.drop_column('test_finale')
        batch_op.drop_column('punteggio_minimo')
        batch_op.drop_column('test_iniziale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_iniziale', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('punteggio_minimo', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('test_finale', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
