"""Aggiunti campi per test e tabella risultati test

Revision ID: c259fa95b84f
Revises: f9f83401bd5a
Create Date: 2025-03-05 20:53:57.860676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c259fa95b84f'
down_revision = 'f9f83401bd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_risultato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discente_id', sa.Integer(), nullable=False),
    sa.Column('corso_id', sa.Integer(), nullable=False),
    sa.Column('punteggio_ottenuto', sa.Integer(), nullable=False),
    sa.Column('superato', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['corso_id'], ['corso.id'], ),
    sa.ForeignKeyConstraint(['discente_id'], ['discente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_iniziale', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('test_finale', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('punteggio_minimo', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corso', schema=None) as batch_op:
        batch_op.drop_column('punteggio_minimo')
        batch_op.drop_column('test_finale')
        batch_op.drop_column('test_iniziale')

    op.drop_table('test_risultato')
    # ### end Alembic commands ###
