"""Ricreazione delle tabelle

Revision ID: f9f83401bd5a
Revises: bd5a737feeeb
Create Date: 2025-03-05 15:02:15.567234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f83401bd5a'
down_revision = 'bd5a737feeeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descrizione', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corso', schema=None) as batch_op:
        batch_op.drop_column('descrizione')

    # ### end Alembic commands ###
